// Generated from bingo-improve/schema/rpc.json; do not edit.
// SHA-256: d90a354bee2f1090918356a3d59450b96e80df205c060b39f13235a5d826cd21
import { z } from 'zod'
import type { RpcMethod } from '../../shared/rpc'

const definitions: Record<string, z.ZodType> = {
  Action: z.looseObject({ "name": z.string(), "args": z.json().optional() }),
  ActionItem: z.looseObject({ "label": z.string(), "action": z.lazy(() => definitions.Action), "key": z.union([z.string().min(1).max(1), z.null()]).optional() }),
  Activation: z.enum(["keyboard","pointer","programmatic"]),
  Answer: z.union([z.looseObject({ "kind": z.literal("allowOnce") }), z.looseObject({ "scope": z.string(), "kind": z.literal("allowSession") }), z.looseObject({ "feedback": z.union([z.string(), z.null()]).optional(), "kind": z.literal("deny") }), z.looseObject({ "ids": z.array(z.string()), "other": z.union([z.string(), z.null()]).optional(), "kind": z.literal("choice") }), z.looseObject({ "text": z.string(), "kind": z.literal("text") }), z.looseObject({ "kind": z.literal("confirm") }), z.looseObject({ "kind": z.literal("cancel") }), z.looseObject({ "answers": z.array(z.lazy(() => definitions.Answer)), "kind": z.literal("form") })]),
  AnswerParams: z.looseObject({ "session": z.lazy(() => definitions.SessionId), "intent": z.lazy(() => definitions.IntentId), "interaction": z.lazy(() => definitions.InteractionId), "answer": z.lazy(() => definitions.Answer), "activation": z.lazy(() => definitions.Activation) }),
  AnswerRole: z.union([z.literal("allowing"), z.literal("refusing")]),
  AnswerSpec: z.enum(["allowOnce","allowSession","deny","choice","text","confirm","cancel","form"]),
  CancelReason: z.union([z.enum(["turnEnded","interrupted","sessionClosed","expired","superseded"]), z.literal("commandEnded")]),
  Capabilities: z.looseObject({ "methods": z.array(z.string()), "notifications": z.array(z.string()) }),
  Catalog: z.looseObject({ "kind": z.lazy(() => definitions.CatalogKind), "entries": z.array(z.lazy(() => definitions.CatalogEntry)) }),
  CatalogEntry: z.looseObject({ "id": z.string(), "label": z.string(), "meta": z.json().optional() }),
  CatalogKind: z.enum(["models","providers","tools","commands","skills","plugins"]),
  CatalogParams: z.looseObject({ "kind": z.lazy(() => definitions.CatalogKind) }),
  ClientIdentity: z.looseObject({ "name": z.string(), "surface": z.string() }),
  CloseReason: z.union([z.looseObject({ "kind": z.literal("client") }), z.looseObject({ "kind": z.literal("shutdown") }), z.looseObject({ "kind": z.literal("deleted") }), z.looseObject({ "message": z.string(), "kind": z.literal("error") })]),
  ConfigView: z.looseObject({ "kernel": z.json().optional(), "plugins": z.record(z.string(), z.json()).optional() }),
  ContentPart: z.union([z.looseObject({ "text": z.string(), "type": z.literal("text") }), z.intersection(z.lazy(() => definitions.Image), z.looseObject({ "type": z.literal("image") })), z.looseObject({ "id": z.string(), "name": z.string(), "input": z.json(), "type": z.literal("toolUse") }), z.looseObject({ "toolUseId": z.string(), "parts": z.array(z.lazy(() => definitions.ContentPart)), "isError": z.boolean().optional(), "type": z.literal("toolResult") }), z.looseObject({ "text": z.string(), "providerMetadata": z.record(z.string(), z.record(z.string(), z.json())).optional(), "type": z.literal("reasoning") })]),
  ContextUsage: z.looseObject({ "used": z.number().int().safe().min(0), "window": z.number().int().safe().min(0), "trigger": z.number().int().safe().min(0) }),
  DecisionKind: z.enum(["allow","allowSession","deny"]),
  DeliverParams: z.looseObject({ "session": z.lazy(() => definitions.SessionId), "intent": z.lazy(() => definitions.IntentId), "input": z.lazy(() => definitions.Input), "delivery": z.lazy(() => definitions.Delivery) }),
  Delivery: z.union([z.literal("wake"), z.literal("hold")]),
  DeltaKind: z.union([z.literal("text"), z.literal("reasoning"), z.literal("tail")]),
  Driver: z.union([z.literal("model"), z.literal("log")]),
  Empty: z.looseObject({  }),
  ErrorCode: z.union([z.enum(["SESSION_NOT_FOUND","SESSION_LOCKED","SESSION_CLOSED","INTERACTION_CLOSED","NOT_READY","STALE_GENERATION","NOT_INITIALIZED","INVALID_INPUT","PERMISSION_DENIED","TOOL_NOT_FOUND","TOOL_FAILED","PROVIDER_UNAVAILABLE","AUTH_REQUIRED","RATE_LIMITED","CONTEXT_OVERFLOW","TIMEOUT","OFFLINE","SERVER_ERROR","TURN_LOST","TURN_BUDGET_EXHAUSTED","INTERNAL"]), z.literal("NOT_FOUND"), z.literal("STORAGE")]),
  Event: z.union([z.looseObject({ "summary": z.lazy(() => definitions.SessionSummary), "type": z.literal("sessionUpdated") }), z.looseObject({ "reason": z.lazy(() => definitions.CloseReason), "type": z.literal("sessionClosed") }), z.looseObject({ "turn": z.lazy(() => definitions.TurnId), "inputs": z.array(z.lazy(() => definitions.ItemId)), "origin": z.lazy(() => definitions.TurnOrigin), "type": z.literal("turnStarted") }), z.looseObject({ "turn": z.lazy(() => definitions.TurnId), "attempt": z.number().int().safe().min(0), "max": z.number().int().safe().min(0), "delayMs": z.number().int().safe().min(0), "dropped": z.array(z.lazy(() => definitions.ItemId)), "reason": z.string(), "type": z.literal("turnRetrying") }), z.looseObject({ "turn": z.lazy(() => definitions.TurnId), "usage": z.lazy(() => definitions.Usage), "context": z.lazy(() => definitions.ContextUsage), "type": z.literal("turnUsage") }), z.looseObject({ "turn": z.lazy(() => definitions.TurnId), "status": z.lazy(() => definitions.TurnStatus), "usage": z.lazy(() => definitions.Usage), "type": z.literal("turnCompleted") }), z.looseObject({ "item": z.lazy(() => definitions.Item), "type": z.literal("itemStarted") }), z.looseObject({ "item": z.lazy(() => definitions.ItemId), "n": z.number().int().safe().min(0), "kind": z.lazy(() => definitions.DeltaKind), "data": z.string(), "type": z.literal("itemDelta") }), z.looseObject({ "item": z.lazy(() => definitions.Item), "type": z.literal("itemUpdated") }), z.looseObject({ "item": z.lazy(() => definitions.Item), "type": z.literal("itemCompleted") }), z.looseObject({ "revision": z.number().int().safe().min(0), "entries": z.array(z.lazy(() => definitions.QueueEntry)), "type": z.literal("queueChanged") }), z.looseObject({ "interaction": z.lazy(() => definitions.Interaction), "type": z.literal("interactionOpened") }), z.looseObject({ "id": z.lazy(() => definitions.InteractionId), "answer": z.lazy(() => definitions.Answer), "by": z.lazy(() => definitions.ResolvedBy), "type": z.literal("interactionResolved") }), z.looseObject({ "id": z.lazy(() => definitions.InteractionId), "reason": z.lazy(() => definitions.CancelReason), "type": z.literal("interactionCancelled") }), z.looseObject({ "intent": z.lazy(() => definitions.IntentId), "outcome": z.lazy(() => definitions.IntentOutcome), "type": z.literal("intentAck") }), z.looseObject({ "generation": z.number().int().safe().min(0), "boundary": z.lazy(() => definitions.ItemId), "summary": z.lazy(() => definitions.ItemId), "kept": z.array(z.lazy(() => definitions.ItemId)), "type": z.literal("compacted") }), z.looseObject({ "generation": z.number().int().safe().min(0), "toTurn": z.lazy(() => definitions.TurnId), "dropped": z.array(z.lazy(() => definitions.ItemId)), "filesRestored": z.array(z.string()), "type": z.literal("rewound") }), z.looseObject({ "config": z.lazy(() => definitions.ConfigView), "type": z.literal("configChanged") }), z.looseObject({ "kind": z.string(), "type": z.literal("catalogChanged") }), z.looseObject({ "level": z.lazy(() => definitions.Level), "code": z.string(), "text": z.string(), "type": z.literal("notice") }), z.looseObject({ "plugin": z.string(), "kind": z.string(), "payload": z.json(), "type": z.literal("extension") }), z.looseObject({ "plugin": z.string(), "kind": z.string(), "payload": z.json(), "type": z.literal("signal") }), z.looseObject({ "from": z.lazy(() => definitions.Seq), "to": z.lazy(() => definitions.Seq), "type": z.literal("lagged") })]),
  EventParams: z.looseObject({ "seq": z.lazy(() => definitions.Seq), "ts": z.string(), "session": z.lazy(() => definitions.SessionId), "cause": z.union([z.lazy(() => definitions.IntentId), z.null()]).optional(), "event": z.lazy(() => definitions.Event), "root": z.union([z.lazy(() => definitions.SessionId), z.null()]).optional() }),
  EventsParams: z.looseObject({ "session": z.lazy(() => definitions.SessionId), "since": z.lazy(() => definitions.Seq).optional() }),
  ExtendParams: z.looseObject({ "session": z.lazy(() => definitions.SessionId), "plugin": z.string(), "kind": z.string(), "payload": z.json() }),
  GatewayEvent: z.union([z.looseObject({ "summary": z.lazy(() => definitions.SessionSummary), "type": z.literal("sessionCreated") }), z.looseObject({ "session": z.lazy(() => definitions.SessionId), "type": z.literal("sessionRemoved") }), z.looseObject({ "kind": z.lazy(() => definitions.CatalogKind), "type": z.literal("catalogChanged") })]),
  HistoryChunk: z.looseObject({ "items": z.array(z.lazy(() => definitions.Item)), "next": z.union([z.lazy(() => definitions.ItemId), z.null()]).optional(), "generation": z.number().int().safe().min(0) }),
  HistoryPage: z.looseObject({ "before": z.union([z.lazy(() => definitions.ItemId), z.null()]).optional(), "limit": z.number().int().safe().min(0).optional() }),
  HistoryParams: z.looseObject({ "session": z.lazy(() => definitions.SessionId), "page": z.lazy(() => definitions.HistoryPage).optional() }),
  Image: z.looseObject({ "mediaType": z.string(), "data": z.string() }),
  InitializeParams: z.looseObject({ "client": z.lazy(() => definitions.ClientIdentity), "protocol": z.number().int().safe().min(0) }),
  InitializeResult: z.looseObject({ "protocol": z.number().int().safe().min(0), "name": z.string(), "version": z.string(), "capabilities": z.lazy(() => definitions.Capabilities) }),
  Input: z.union([z.looseObject({ "text": z.string(), "images": z.array(z.lazy(() => definitions.Image)).optional(), "origin": z.lazy(() => definitions.Origin), "delivery": z.lazy(() => definitions.Delivery).optional(), "kind": z.literal("text") }), z.looseObject({ "action": z.lazy(() => definitions.Action), "kind": z.literal("action") })]),
  IntentId: z.string(),
  IntentOutcome: z.union([z.looseObject({ "turn": z.lazy(() => definitions.TurnId), "kind": z.literal("turnStarted") }), z.looseObject({ "position": z.number().int().safe().min(0), "kind": z.literal("queued") }), z.looseObject({ "result": z.json(), "kind": z.literal("applied") }), z.looseObject({ "error": z.lazy(() => definitions.KernelError), "kind": z.literal("rejected") })]),
  Interaction: z.looseObject({ "id": z.lazy(() => definitions.InteractionId), "session": z.lazy(() => definitions.SessionId), "turn": z.union([z.lazy(() => definitions.TurnId), z.null()]).optional(), "item": z.union([z.lazy(() => definitions.ItemId), z.null()]).optional(), "openedAt": z.string(), "guardUntil": z.union([z.string(), z.null()]).optional(), "expiresAt": z.union([z.string(), z.null()]).optional(), "kind": z.lazy(() => definitions.InteractionKind), "answers": z.array(z.lazy(() => definitions.AnswerSpec)) }),
  InteractionId: z.string(),
  InteractionKind: z.union([z.looseObject({ "tool": z.string(), "summary": z.string(), "preview": z.union([z.lazy(() => definitions.Preview), z.null()]).optional(), "sessionScope": z.union([z.string(), z.null()]).optional(), "kind": z.literal("permission") }), z.intersection(z.lazy(() => definitions.Question), z.looseObject({ "kind": z.literal("question") })), z.looseObject({ "title": z.union([z.string(), z.null()]).optional(), "questions": z.array(z.lazy(() => definitions.Question)), "kind": z.literal("form") }), z.looseObject({ "title": z.string(), "detail": z.string(), "kind": z.literal("confirm") }), z.looseObject({ "provider": z.string(), "flow": z.lazy(() => definitions.LoginFlow), "kind": z.literal("login") })]),
  InterruptParams: z.looseObject({ "session": z.lazy(() => definitions.SessionId), "intent": z.lazy(() => definitions.IntentId), "scope": z.lazy(() => definitions.InterruptScope) }),
  InterruptReason: z.enum(["userCancel","newInput","shutdown","budget"]),
  InterruptScope: z.union([z.looseObject({ "turn": z.lazy(() => definitions.TurnId), "kind": z.literal("turn") }), z.looseObject({ "kind": z.literal("head") })]),
  Item: z.looseObject({ "id": z.lazy(() => definitions.ItemId), "turn": z.union([z.lazy(() => definitions.TurnId), z.null()]).optional(), "round": z.number().int().safe().min(0).optional(), "status": z.lazy(() => definitions.ItemStatus), "startedAt": z.string(), "completedAt": z.union([z.string(), z.null()]).optional(), "intent": z.union([z.lazy(() => definitions.IntentId), z.null()]).optional(), "body": z.lazy(() => definitions.ItemBody), "meta": z.record(z.string(), z.json()).optional() }),
  ItemBody: z.union([z.looseObject({ "parts": z.array(z.lazy(() => definitions.ContentPart)), "origin": z.lazy(() => definitions.Origin), "kind": z.literal("user") }), z.looseObject({ "text": z.string(), "kind": z.literal("assistant") }), z.looseObject({ "text": z.string(), "providerMetadata": z.record(z.string(), z.record(z.string(), z.json())).optional(), "kind": z.literal("reasoning") }), z.looseObject({ "callId": z.string(), "name": z.string(), "input": z.json(), "output": z.union([z.lazy(() => definitions.ToolOutput), z.null()]).optional(), "progress": z.union([z.string(), z.null()]).optional(), "durationMs": z.union([z.number().int().safe().min(0), z.null()]).optional(), "kind": z.literal("toolCall") }), z.looseObject({ "command": z.string(), "output": z.string(), "exit": z.union([z.number().int().safe(), z.null()]).optional(), "cwd": z.string(), "kind": z.literal("shell") }), z.looseObject({ "name": z.string(), "args": z.json().optional(), "result": z.json().optional(), "kind": z.literal("action") }), z.looseObject({ "summary": z.string(), "replaced": z.number().int().safe().min(0), "before": z.number().int().safe().min(0), "after": z.number().int().safe().min(0), "durationMs": z.number().int().safe().min(0), "kind": z.literal("compaction") }), z.looseObject({ "toTurn": z.lazy(() => definitions.TurnId), "dropped": z.number().int().safe().min(0), "kind": z.literal("rewind") }), z.looseObject({ "marker": z.string(), "kind": z.literal("interruption") }), z.looseObject({ "level": z.lazy(() => definitions.Level), "code": z.string(), "text": z.string(), "kind": z.literal("notice") }), z.looseObject({ "interaction": z.lazy(() => definitions.InteractionId), "question": z.string(), "answer": z.string(), "kind": z.literal("questionAnswer") }), z.looseObject({ "interaction": z.lazy(() => definitions.InteractionId), "tool": z.string(), "decision": z.lazy(() => definitions.DecisionKind), "feedback": z.union([z.string(), z.null()]).optional(), "kind": z.literal("permissionReceipt") }), z.looseObject({ "asset": z.string(), "label": z.union([z.string(), z.null()]).optional(), "kind": z.literal("asset") })]),
  ItemId: z.string(),
  ItemStatus: z.enum(["pending","running","completed","failed","interrupted"]),
  KernelError: z.looseObject({ "code": z.lazy(() => definitions.ErrorCode), "message": z.string() }),
  Level: z.enum(["info","warn","error"]),
  ListParams: z.looseObject({ "filter": z.lazy(() => definitions.SessionFilter).optional() }),
  ListResult: z.looseObject({ "sessions": z.array(z.lazy(() => definitions.SessionSummary)) }),
  LiveTurn: z.looseObject({ "id": z.lazy(() => definitions.TurnId), "startedAt": z.string(), "origin": z.lazy(() => definitions.TurnOrigin), "round": z.number().int().safe().min(0).optional(), "usage": z.lazy(() => definitions.Usage).optional(), "retrying": z.union([z.lazy(() => definitions.Retry), z.null()]).optional() }),
  LoginFlow: z.union([z.looseObject({ "url": z.string(), "kind": z.literal("browser") }), z.looseObject({ "url": z.string(), "code": z.string(), "kind": z.literal("device") }), z.looseObject({ "kind": z.literal("paste") })]),
  OpenOptions: z.looseObject({ "children": z.boolean().optional() }),
  OpenParams: z.looseObject({ "selector": z.lazy(() => definitions.SessionSelector), "options": z.lazy(() => definitions.OpenOptions).optional() }),
  OpenResult: z.looseObject({ "session": z.lazy(() => definitions.SessionId), "snapshot": z.lazy(() => definitions.SessionState) }),
  Origin: z.looseObject({ "surface": z.string(), "principal": z.union([z.string(), z.null()]).optional(), "conversation": z.union([z.string(), z.null()]).optional() }),
  ParentLink: z.looseObject({ "session": z.lazy(() => definitions.SessionId), "item": z.union([z.lazy(() => definitions.ItemId), z.null()]).optional() }),
  Preview: z.union([z.looseObject({ "unified": z.string(), "kind": z.literal("diff") }), z.looseObject({ "command": z.string(), "cwd": z.string(), "kind": z.literal("command") }), z.looseObject({ "url": z.string(), "kind": z.literal("url") })]),
  Question: z.looseObject({ "question": z.string(), "header": z.union([z.string(), z.null()]).optional(), "options": z.array(z.lazy(() => definitions.QuestionOption)), "freeText": z.boolean().optional(), "multi": z.boolean().optional() }),
  QuestionOption: z.looseObject({ "id": z.string(), "label": z.string(), "description": z.union([z.string(), z.null()]).optional(), "role": z.union([z.lazy(() => definitions.AnswerRole), z.null()]).optional(), "preview": z.union([z.string(), z.null()]).optional() }),
  QueueEntry: z.looseObject({ "intent": z.lazy(() => definitions.IntentId), "position": z.number().int().safe().min(0), "preview": z.string(), "steerable": z.boolean(), "origin": z.lazy(() => definitions.Origin) }),
  ResolvedBy: z.union([z.looseObject({ "name": z.string(), "surface": z.string(), "kind": z.literal("client") }), z.looseObject({ "kind": z.literal("kernel") }), z.looseObject({ "kind": z.literal("policy") })]),
  Retry: z.looseObject({ "attempt": z.number().int().safe().min(0), "max": z.number().int().safe().min(0) }),
  Seq: z.number().int().safe().min(0),
  SessionFilter: z.looseObject({ "cwd": z.union([z.string(), z.null()]).optional(), "parent": z.union([z.lazy(() => definitions.SessionId), z.null()]).optional(), "limit": z.union([z.number().int().safe().min(0), z.null()]).optional() }),
  SessionId: z.string(),
  SessionParams: z.looseObject({ "session": z.lazy(() => definitions.SessionId) }),
  SessionSelector: z.union([z.looseObject({ "spec": z.lazy(() => definitions.SessionSpec), "kind": z.literal("create") }), z.looseObject({ "id": z.lazy(() => definitions.SessionId), "kind": z.literal("byId") }), z.looseObject({ "key": z.string(), "kind": z.literal("byKey") }), z.looseObject({ "cwd": z.string(), "kind": z.literal("latest") })]),
  SessionSpec: z.looseObject({ "cwd": z.string(), "key": z.union([z.string(), z.null()]).optional(), "parent": z.union([z.lazy(() => definitions.ParentLink), z.null()]).optional(), "title": z.union([z.string(), z.null()]).optional(), "driver": z.lazy(() => definitions.Driver).optional(), "provider": z.union([z.string(), z.null()]).optional(), "model": z.union([z.string(), z.null()]).optional(), "systemExtra": z.union([z.string(), z.null()]).optional(), "tools": z.union([z.array(z.string()), z.null()]).optional() }),
  SessionState: z.looseObject({ "seq": z.lazy(() => definitions.Seq), "summary": z.lazy(() => definitions.SessionSummary), "config": z.lazy(() => definitions.ConfigView).optional(), "historyGeneration": z.number().int().safe().min(0).optional(), "items": z.array(z.lazy(() => definitions.Item)), "turn": z.union([z.lazy(() => definitions.LiveTurn), z.null()]).optional(), "queue": z.array(z.lazy(() => definitions.QueueEntry)).optional(), "interactions": z.array(z.lazy(() => definitions.Interaction)).optional(), "context": z.union([z.lazy(() => definitions.ContextUsage), z.null()]).optional(), "lastTurn": z.union([z.lazy(() => definitions.TurnStatus), z.null()]).optional(), "unread": z.boolean().optional(), "closed": z.boolean().optional(), "extensions": z.record(z.string(), z.record(z.string(), z.json())).optional(), "signals": z.record(z.string(), z.record(z.string(), z.json())).optional() }),
  SessionSummary: z.looseObject({ "id": z.lazy(() => definitions.SessionId), "key": z.union([z.string(), z.null()]).optional(), "title": z.union([z.string(), z.null()]).optional(), "cwd": z.string(), "parent": z.union([z.lazy(() => definitions.ParentLink), z.null()]).optional(), "driver": z.lazy(() => definitions.Driver).optional(), "model": z.union([z.string(), z.null()]).optional(), "systemExtra": z.union([z.string(), z.null()]).optional(), "tools": z.union([z.array(z.string()), z.null()]).optional(), "provider": z.union([z.string(), z.null()]).optional(), "createdAt": z.string(), "updatedAt": z.string(), "usage": z.lazy(() => definitions.Usage).optional(), "busy": z.boolean().optional(), "messages": z.union([z.number().int().safe().min(0), z.null()]).optional() }),
  SignalParams: z.looseObject({ "session": z.lazy(() => definitions.SessionId), "plugin": z.string(), "kind": z.string(), "payload": z.json() }),
  SubmitParams: z.looseObject({ "session": z.lazy(() => definitions.SessionId), "intent": z.lazy(() => definitions.IntentId), "input": z.lazy(() => definitions.Input) }),
  Tone: z.union([z.enum(["neutral","good","bad"]), z.literal("attention")]),
  ToolOutput: z.looseObject({ "parts": z.array(z.lazy(() => definitions.ContentPart)), "isError": z.boolean().optional(), "display": z.union([z.lazy(() => definitions.View), z.null()]).optional() }),
  TreeNode: z.looseObject({ "label": z.string(), "badge": z.union([z.string(), z.null()]).optional(), "tone": z.lazy(() => definitions.Tone).optional(), "children": z.array(z.lazy(() => definitions.TreeNode)).optional() }),
  TurnId: z.string(),
  TurnOrigin: z.union([z.literal("submit"), z.literal("queue"), z.literal("peer"), z.literal("auto")]),
  TurnStatus: z.union([z.looseObject({ "kind": z.literal("completed") }), z.looseObject({ "error": z.lazy(() => definitions.KernelError), "kind": z.literal("failed") }), z.looseObject({ "reason": z.lazy(() => definitions.InterruptReason), "kind": z.literal("interrupted") })]),
  Usage: z.looseObject({ "inputTokens": z.number().int().safe().min(0), "outputTokens": z.number().int().safe().min(0), "cacheReadTokens": z.number().int().safe().min(0).optional(), "cacheWriteTokens": z.number().int().safe().min(0).optional(), "reasoningTokens": z.number().int().safe().min(0).optional() }),
  View: z.union([z.looseObject({ "text": z.string(), "kind": z.literal("text") }), z.looseObject({ "text": z.string(), "kind": z.literal("markdown") }), z.looseObject({ "lang": z.union([z.string(), z.null()]).optional(), "text": z.string(), "kind": z.literal("code") }), z.looseObject({ "unified": z.string(), "kind": z.literal("diff") }), z.looseObject({ "items": z.array(z.string()), "kind": z.literal("list") }), z.looseObject({ "headers": z.array(z.string()), "rows": z.array(z.array(z.string())), "kind": z.literal("table") }), z.looseObject({ "rows": z.array(z.tuple([z.string(), z.string()])), "kind": z.literal("keyValue") }), z.looseObject({ "value": z.number().int().safe().min(0), "total": z.union([z.number().int().safe().min(0), z.null()]).optional(), "label": z.union([z.string(), z.null()]).optional(), "kind": z.literal("progress") }), z.looseObject({ "text": z.string(), "tone": z.lazy(() => definitions.Tone).optional(), "kind": z.literal("badge") }), z.looseObject({ "nodes": z.array(z.lazy(() => definitions.TreeNode)), "kind": z.literal("tree") }), z.looseObject({ "children": z.array(z.lazy(() => definitions.View)), "kind": z.literal("stack") }), z.looseObject({ "children": z.array(z.lazy(() => definitions.View)), "kind": z.literal("columns") }), z.looseObject({ "title": z.string(), "child": z.lazy(() => definitions.View), "kind": z.literal("panel") }), z.looseObject({ "items": z.array(z.lazy(() => definitions.ActionItem)), "kind": z.literal("actions") }), z.looseObject({ "customKind": z.string(), "data": z.json(), "fold": z.string(), "kind": z.literal("custom") })])
}

export const rpcParamsSchemas: Record<RpcMethod, z.ZodType> = {
  "initialize": z.lazy(() => definitions.InitializeParams),
  "shutdown": z.lazy(() => definitions.Empty),
  "session/list": z.lazy(() => definitions.ListParams),
  "session/open": z.lazy(() => definitions.OpenParams),
  "session/close": z.lazy(() => definitions.SessionParams),
  "session/delete": z.lazy(() => definitions.SessionParams),
  "session/deliver": z.lazy(() => definitions.DeliverParams),
  "session/extend": z.lazy(() => definitions.ExtendParams),
  "session/signal": z.lazy(() => definitions.SignalParams),
  "session/history": z.lazy(() => definitions.HistoryParams),
  "session/events": z.lazy(() => definitions.EventsParams),
  "session/submit": z.lazy(() => definitions.SubmitParams),
  "session/interrupt": z.lazy(() => definitions.InterruptParams),
  "session/answer": z.lazy(() => definitions.AnswerParams),
  "catalog/read": z.lazy(() => definitions.CatalogParams),
  "gateway/subscribe": z.lazy(() => definitions.Empty)
}

export const rpcResultSchemas: Record<RpcMethod, z.ZodType> = {
  "initialize": z.lazy(() => definitions.InitializeResult),
  "shutdown": z.lazy(() => definitions.Empty),
  "session/list": z.lazy(() => definitions.ListResult),
  "session/open": z.lazy(() => definitions.OpenResult),
  "session/close": z.lazy(() => definitions.Empty),
  "session/delete": z.lazy(() => definitions.Empty),
  "session/deliver": z.lazy(() => definitions.Empty),
  "session/extend": z.lazy(() => definitions.Empty),
  "session/signal": z.lazy(() => definitions.Empty),
  "session/history": z.lazy(() => definitions.HistoryChunk),
  "session/events": z.lazy(() => definitions.Empty),
  "session/submit": z.lazy(() => definitions.Empty),
  "session/interrupt": z.lazy(() => definitions.Empty),
  "session/answer": z.lazy(() => definitions.Empty),
  "catalog/read": z.lazy(() => definitions.Catalog),
  "gateway/subscribe": z.lazy(() => definitions.Empty)
}

export const rpcNotificationSchemas = {
  "event": z.lazy(() => definitions.EventParams),
  "gateway/event": z.lazy(() => definitions.GatewayEvent)
}
